apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-users
  template:
    metadata:
      labels:
        app: fastapi-users
    spec:
      containers:
        - name: fastapi
          image: mahdi041196/fastapi-users:1.0
          ports:
            - containerPort: 8000
